name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: devops_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # متغیرهای اتصال به دیتابیس برای Django
      DATABASE_NAME: devops_db
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Migrations
        env:
          # اینجا هم متغیرهای دیتابیس رو می‌تونی بده اگر نیاز هست
          DATABASE_NAME: devops_db
          DATABASE_USER: user
          DATABASE_PASSWORD: pass
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: python manage.py migrate

      - name: Run Tests
        env:
          DATABASE_NAME: devops_db
          DATABASE_USER: user
          DATABASE_PASSWORD: pass
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mrezadeveloper/my-django-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push mrezadeveloper/my-django-app:latest
