name: Docker CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mrezadeveloper/myapp:latest .

      - name: Run tests inside container
        run: docker run --rm mrezadeveloper/myapp:latest

      - name: Push Docker image to DockerHub
        run: docker push mrezadeveloper/myapp:latest

      - name: Deploy to Server via SSH
        if: success() && env.SERVER_IP != ''
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull mrezadeveloper/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 mrezadeveloper/myapp:latest
