# .github/workflows/deploy.yml
name: Deploy to Railway

on:
  push:
    branches: [main]  # ?? ?? ????? ?? ???? ?????? ??????? ??????

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token $RAILWAY_TOKEN

      - name: Link to Railway project and service
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT }} --service ${{ secrets.RAILWAY_SERVICE }}

      - name: Deploy to Railway
        run: railway up
